//
//  ChummerXMLExporter.swift
//  ShadowDeck
//
//  Phase 9B — best-effort .chum5 XML export for online hubs.
//  When import provenance retains the original payload, that is preferred.
//

import Foundation

public enum ChummerExportMode: String, Sendable {
    /// Prefer original imported bytes when available.
    case preferOriginal
    /// Always regenerate from ShadowDeck domain model.
    case regeneratedOnly
}

public struct ChummerExportResult: Sendable {
    public var xmlData: Data
    public var fidelity: ExportFidelityReport
    public var usedOriginalPayload: Bool
}

public struct ExportFidelityReport: Sendable {
    public var included: [String]
    public var omitted: [String]
    public var notes: [String]

    public var summary: String {
        var lines: [String] = []
        lines.append("Included: \(included.joined(separator: ", "))")
        if !omitted.isEmpty {
            lines.append("Omitted / limited: \(omitted.joined(separator: ", "))")
        }
        lines.append(contentsOf: notes)
        return lines.joined(separator: "\n")
    }
}

public enum ChummerXMLExporter {
    public static func export(
        _ character: Character,
        mode: ChummerExportMode = .preferOriginal
    ) throws -> ChummerExportResult {
        if mode == .preferOriginal,
           let payload = character.importProvenance?.originalPayload,
           !payload.isEmpty,
           isLikelyChummerXML(payload)
        {
            return ChummerExportResult(
                xmlData: payload,
                fidelity: ExportFidelityReport(
                    included: ["original import payload (byte-faithful)"],
                    omitted: [],
                    notes: [
                        "Exported the original Chummer file stored at import time.",
                        "File name hint: \(character.importProvenance?.originalFileName ?? "—").",
                    ]
                ),
                usedOriginalPayload: true
            )
        }
        let generated = try generate(character)
        return ChummerExportResult(
            xmlData: generated.xmlData,
            fidelity: generated.fidelity,
            usedOriginalPayload: false
        )
    }

    public static func write(
        _ character: Character,
        to url: URL,
        mode: ChummerExportMode = .preferOriginal
    ) throws -> ExportFidelityReport {
        let result = try export(character, mode: mode)
        try result.xmlData.write(to: url, options: .atomic)
        return result.fidelity
    }

    // MARK: - Generated export

    private static func generate(_ character: Character) throws -> (xmlData: Data, fidelity: ExportFidelityReport) {
        let report = CampaignSheetReport.build(for: character)
        let c = character
        let eff = report.effects.effectiveAttributes
        let profile = MetatypeCatalog.profile(for: c.metatype, edition: c.edition)

        var included: [String] = [
            "identity", "attributes", "newskills", "qualities", "cyberwares", "biowares",
            "gears", "weapons", "armors", "contacts", "nuyen", "karma", "awakened flags",
        ]
        var omitted: [String] = [
            "full Chummer UI settings hash",
            "improvement/bonus tree",
            "zero-rank skill catalog dump",
            "vehicle accessory trees",
            "mugshots binary",
        ]
        var notes: [String] = [
            "Regenerated by ShadowDeck — best-effort compatibility, not official Chummer format guarantee.",
            "Attribute base = ShadowDeck base; totalvalue = effective (base + modifiers).",
            "Skills written under <newskills><skills> (Chummer 5.x modern layout).",
        ]

        if !c.adeptPowers.isEmpty { included.append("powers") }
        if !c.spells.isEmpty { included.append("spells") }
        if !c.complexForms.isEmpty { included.append("complexforms") }
        if !c.lifestyles.isEmpty { included.append("lifestyles") }

        var xml = ""
        xml += "\u{FEFF}" // BOM like Ghostwire
        xml += "<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n"
        xml += "<character>\r\n"
        xml += "  <createdversion>5.225.0</createdversion>\r\n"
        xml += "  <appversion>ShadowDeck</appversion>\r\n"
        xml += elem("gameedition", gameEdition(c.edition), indent: 2)
        xml += elem("buildmethod", c.generation.system.displayName, indent: 2)
        xml += prioritiesXML(c)
        xml += elem("name", c.name, indent: 2)
        xml += elem("alias", c.streetName, indent: 2)
        xml += elem("metatype", c.metatype.displayName, indent: 2)
        xml += elem("metatypecategory", "Metahuman", indent: 2)
        xml += elem("concept", c.concept, indent: 2)
        xml += elem("nuyen", "\(c.nuyen)", indent: 2)
        xml += elem("karma", "\(c.karmaAvailable)", indent: 2)
        xml += elem("totalkarma", "\(c.karmaTotal)", indent: 2)
        xml += elem("adept", bool(c.awakened == .adept || c.awakened == .mysticAdept), indent: 2)
        xml += elem("magician", bool(c.awakened.usesMagic && c.awakened != .adept), indent: 2)
        xml += elem("technomancer", bool(c.awakened == .technomancer), indent: 2)
        xml += elem("mysticadept", bool(c.awakened == .mysticAdept), indent: 2)
        xml += elem("totaless", formatDecimal(report.derived.currentEssence), indent: 2)
        if let bg = c.background, !bg.isEmpty {
            xml += elem("background", bg, indent: 2)
        }

        // Attributes
        xml += "  <attributes>\r\n"
        let attrPairs: [(String, AttributeID)] = [
            ("BOD", .body), ("AGI", .agility), ("REA", .reaction), ("STR", .strength),
            ("CHA", .charisma), ("INT", .intuition), ("LOG", .logic), ("WIL", .willpower),
            ("EDG", .edge), ("MAG", .magic), ("RES", .resonance),
        ]
        for (name, id) in attrPairs {
            let bounds = profile.bounds(for: id)
            let base = c.attributes[id]
            let total = eff[id]
            xml += "    <attribute>\r\n"
            xml += elem("name", name, indent: 6)
            xml += elem("metatypemin", "\(bounds.minimum)", indent: 6)
            xml += elem("metatypemax", "\(bounds.maximum)", indent: 6)
            xml += elem("metatypeaugmax", "\(bounds.maximum + 4)", indent: 6)
            xml += elem("base", "\(base)", indent: 6)
            xml += elem("karma", "0", indent: 6)
            xml += elem("totalvalue", "\(total)", indent: 6)
            xml += "    </attribute>\r\n"
        }
        xml += "  </attributes>\r\n"

        // newskills (modern Chummer layout)
        xml += "  <newskills>\r\n"
        xml += "    <skills>\r\n"
        for skill in c.skills where skill.rating > 0 && skill.category == .active {
            xml += skillXML(skill)
        }
        xml += "    </skills>\r\n"
        xml += "    <knoskills>\r\n"
        for skill in c.skills where skill.rating > 0 && (skill.category == .knowledge || skill.category == .language) {
            xml += skillXML(skill, knowledge: true)
        }
        xml += "    </knoskills>\r\n"
        if !c.skillGroups.isEmpty {
            xml += "    <groups>\r\n"
            for group in c.skillGroups where group.rating > 0 {
                xml += "      <skillgroup>\r\n"
                xml += elem("name", group.group.displayName, indent: 8)
                xml += elem("base", "\(group.rating)", indent: 8)
                xml += elem("rating", "\(group.rating)", indent: 8)
                xml += "      </skillgroup>\r\n"
            }
            xml += "    </groups>\r\n"
            included.append("skill groups")
        }
        xml += "  </newskills>\r\n"

        // Condition monitor filled boxes (play state)
        if let track = c.conditionTrack, track.physicalDamage > 0 || track.stunDamage > 0 {
            xml += elem("physicalcmfilled", "\(track.physicalDamage)", indent: 2)
            xml += elem("stuncmfilled", "\(track.stunDamage)", indent: 2)
            included.append("condition monitors")
        }

        // Qualities
        xml += "  <qualities>\r\n"
        for q in c.qualities {
            xml += "    <quality>\r\n"
            xml += elem("name", q.name, indent: 6)
            xml += elem("karma", "\(q.karmaValue)", indent: 6)
            xml += elem("qualitytype", q.kind == .positive ? "Positive" : "Negative", indent: 6)
            xml += "    </quality>\r\n"
        }
        xml += "  </qualities>\r\n"

        // Cyber / bio
        xml += "  <cyberwares>\r\n"
        for a in c.augmentations where a.kind == .cyberware {
            xml += augXML(a, tag: "cyberware")
        }
        xml += "  </cyberwares>\r\n"
        xml += "  <biowares>\r\n"
        for a in c.augmentations where a.kind == .bioware {
            xml += augXML(a, tag: "bioware")
        }
        xml += "  </biowares>\r\n"

        // Weapons / armors / other gear
        let weapons = c.gear.filter { $0.category == .weapon }
        let armors = c.gear.filter { $0.category == .armor || $0.category == .clothing }
        let other = c.gear.filter { $0.category != .weapon && $0.category != .armor && $0.category != .clothing }

        xml += "  <weapons>\r\n"
        for g in weapons {
            xml += "    <weapon>\r\n"
            xml += elem("name", g.name, indent: 6)
            xml += elem("category", g.subcategory ?? g.category.displayName, indent: 6)
            if let d = g.damageCode { xml += elem("damage", d, indent: 6) }
            xml += elem("avail", g.availability, indent: 6)
            xml += elem("cost", "\(g.nuyenCost)", indent: 6)
            xml += "    </weapon>\r\n"
        }
        xml += "  </weapons>\r\n"

        xml += "  <armors>\r\n"
        for g in armors {
            xml += "    <armor>\r\n"
            xml += elem("name", g.name, indent: 6)
            if let ar = g.armorRating { xml += elem("armor", "\(ar)", indent: 6) }
            xml += elem("equipped", bool(g.equipped), indent: 6)
            xml += elem("cost", "\(g.nuyenCost)", indent: 6)
            xml += "    </armor>\r\n"
        }
        xml += "  </armors>\r\n"

        xml += "  <gears>\r\n"
        for g in other {
            xml += "    <gear>\r\n"
            xml += elem("name", g.name, indent: 6)
            xml += elem("category", g.subcategory ?? g.category.displayName, indent: 6)
            xml += elem("qty", "\(g.quantity)", indent: 6)
            xml += elem("cost", "\(g.nuyenCost)", indent: 6)
            xml += elem("equipped", bool(g.equipped), indent: 6)
            xml += "    </gear>\r\n"
        }
        xml += "  </gears>\r\n"

        xml += "  <powers>\r\n"
        for p in c.adeptPowers {
            xml += "    <power>\r\n"
            xml += elem("name", p.name, indent: 6)
            xml += elem("rating", "\(p.level)", indent: 6)
            xml += elem("points", formatDecimal(p.powerPointCost), indent: 6)
            xml += "    </power>\r\n"
        }
        xml += "  </powers>\r\n"

        xml += "  <spells>\r\n"
        for s in c.spells {
            xml += "    <spell>\r\n"
            xml += elem("name", s.name, indent: 6)
            xml += elem("category", s.category, indent: 6)
            xml += "    </spell>\r\n"
        }
        xml += "  </spells>\r\n"

        xml += "  <complexforms>\r\n"
        for f in c.complexForms {
            xml += "    <complexform>\r\n"
            xml += elem("name", f.name, indent: 6)
            xml += "    </complexform>\r\n"
        }
        xml += "  </complexforms>\r\n"

        xml += "  <contacts>\r\n"
        for contact in c.contacts {
            xml += "    <contact>\r\n"
            xml += elem("name", contact.name, indent: 6)
            xml += elem("role", contact.role, indent: 6)
            xml += elem("loyalty", "\(contact.loyalty)", indent: 6)
            xml += elem("connection", "\(contact.connection)", indent: 6)
            if let m = contact.metatype { xml += elem("metatype", m, indent: 6) }
            if let loc = contact.location { xml += elem("location", loc, indent: 6) }
            if let g = contact.gender { xml += elem("gender", g, indent: 6) }
            if let a = contact.age { xml += elem("age", a, indent: 6) }
            if let t = contact.contactType, !t.isEmpty {
                xml += elem("type", t, indent: 6)
            }
            if let pay = contact.preferredPayment, !pay.isEmpty {
                xml += elem("preferredpayment", pay, indent: 6)
            }
            if let hobby = contact.hobbiesVice, !hobby.isEmpty {
                xml += elem("hobbiesvice", hobby, indent: 6)
            }
            if let life = contact.personalLife, !life.isEmpty {
                xml += elem("personallife", life, indent: 6)
            }
            if !contact.notes.isEmpty {
                xml += elem("notes", contact.notes, indent: 6)
            }
            // ShadowDeck-only fields (tags, favor, interaction log) intentionally omitted.
            xml += "    </contact>\r\n"
        }
        xml += "  </contacts>\r\n"

        xml += "  <lifestyles>\r\n"
        for life in c.lifestyles {
            xml += "    <lifestyle>\r\n"
            xml += elem("name", life.name, indent: 6)
            xml += elem("baselifestyle", life.level.rawValue, indent: 6)
            xml += elem("cost", "\(life.monthlyCost)", indent: 6)
            xml += elem("months", "\(life.monthsPrepaid)", indent: 6)
            if !life.notes.isEmpty {
                xml += elem("notes", life.notes, indent: 6)
            }
            xml += "    </lifestyle>\r\n"
        }
        xml += "  </lifestyles>\r\n"

        if !c.notes.isEmpty {
            xml += elem("notes", c.notes, indent: 2)
            notes.append("Notes exported as plain text; rich-text formatting may be lost.")
            omitted.append("RTF note formatting")
        }

        xml += "</character>\r\n"

        guard let data = xml.data(using: .utf8) else {
            throw ChummerExportError.encodingFailed
        }
        return (
            data,
            ExportFidelityReport(
                included: included,
                omitted: Array(Set(omitted)).sorted(),
                notes: notes
            )
        )
    }

    private static func skillXML(_ skill: SkillRating, knowledge: Bool = false) -> String {
        var xml = "      <skill>\r\n"
        xml += elem("name", skill.displayName, indent: 8)
        xml += elem("base", "\(skill.rating)", indent: 8)
        xml += elem("karma", "0", indent: 8)
        xml += elem("isknowledge", bool(knowledge || skill.category != .active), indent: 8)
        if skill.category == .language {
            xml += elem("islanguage", "True", indent: 8)
        }
        if let kt = skill.knowledgeType, !kt.isEmpty {
            xml += elem("skillcategory", kt, indent: 8)
        } else if skill.category == .active {
            xml += elem("skillcategory", "Active", indent: 8)
        }
        if let spec = skill.specialized, !spec.isEmpty {
            // Nested form matches modern Chummer 5.x; importer accepts this + flat `<spec>`.
            xml += "        <specs>\r\n"
            xml += "          <spec>\r\n"
            xml += elem("name", spec, indent: 12)
            xml += "          </spec>\r\n"
            xml += "        </specs>\r\n"
        }
        xml += "      </skill>\r\n"
        return xml
    }

    private static func augXML(_ a: Augmentation, tag: String) -> String {
        var xml = "    <\(tag)>\r\n"
        xml += elem("name", a.name, indent: 6)
        xml += elem("ess", formatDecimal(a.essenceCost), indent: 6)
        xml += elem("grade", a.grade.rawValue.capitalized, indent: 6)
        if let r = a.rating { xml += elem("rating", "\(r)", indent: 6) }
        xml += elem("cost", "\(a.nuyenCost)", indent: 6)
        xml += "    </\(tag)>\r\n"
        return xml
    }

    private static func isLikelyChummerXML(_ data: Data) -> Bool {
        let slice = data.prefix(200)
        if let s = String(data: slice, encoding: .utf8)
            ?? String(data: Data(slice.dropFirst(3)), encoding: .utf8)
        {
            return s.contains("<character") || s.contains("<?xml")
        }
        return false
    }

    private static func prioritiesXML(_ c: Character) -> String {
        var s = ""
        func letter(_ col: PriorityColumn) -> String {
            c.generation.priority[col]?.rawValue ?? ""
        }
        s += elem("prioritymetatype", letter(.metatype), indent: 2)
        s += elem("priorityattributes", letter(.attributes), indent: 2)
        s += elem("priorityspecial", letter(.magicOrResonance), indent: 2)
        s += elem("priorityskills", letter(.skills), indent: 2)
        s += elem("priorityresources", letter(.resources), indent: 2)
        return s
    }

    private static func gameEdition(_ edition: Edition) -> String {
        switch edition {
        case .sr4: return "SR4"
        case .sr5: return "SR5"
        case .sr6: return "SR6"
        }
    }

    private static func bool(_ v: Bool) -> String { v ? "True" : "False" }

    private static func formatDecimal(_ d: Decimal) -> String {
        let n = NSDecimalNumber(decimal: d)
        let f = NumberFormatter()
        f.locale = Locale(identifier: "en_US_POSIX")
        f.minimumFractionDigits = 0
        f.maximumFractionDigits = 2
        return f.string(from: n) ?? "\(d)"
    }

    private static func elem(_ name: String, _ value: String, indent: Int) -> String {
        let pad = String(repeating: " ", count: indent)
        return "\(pad)<\(name)>\(escape(value))</\(name)>\r\n"
    }

    private static func escape(_ s: String) -> String {
        s
            .replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
    }
}

public enum ChummerExportError: Error, LocalizedError {
    case encodingFailed

    public var errorDescription: String? {
        switch self {
        case .encodingFailed: "Failed to encode Chummer XML as UTF-8."
        }
    }
}
